// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT the implementation plan.
import { describe, it, expect } from 'vitest';
import { createRegistry, defaultRegistry } from '../../../src/services/component-registry';
import { Component } from '../../../src/component';

class MockComponent extends Component<{ text: string }> {
  render({ text }) { return text; }
}

describe('ComponentRegistry', () => {
  it('should register and retrieve components', () => {
    const registry = createRegistry();
    registry.register('Mock', MockComponent);

    expect(registry.has('Mock')).toBe(true);
    expect(registry.get('Mock')).toBe(MockComponent);
  });

  it('should list registered components', () => {
    const registry = createRegistry();
    registry.register('A', MockComponent);
    registry.register('B', MockComponent);

    expect(registry.list()).toContain('A');
    expect(registry.list()).toContain('B');
  });

  it('should create child registry that inherits', () => {
    const parent = createRegistry();
    parent.register('Parent', MockComponent);

    const child = parent.createChild();
    expect(child.has('Parent')).toBe(true);

    child.register('Child', MockComponent);
    expect(child.has('Child')).toBe(true);
    expect(parent.has('Child')).toBe(false);
  });
});

describe('defaultRegistry', () => {
  it('should be a singleton', () => {
    expect(defaultRegistry).toBeDefined();
  });
});
