// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT the implementation plan.
import { describe, it, expect } from 'vitest';
import { createScope } from '../../../src/services/scope';
import { Component } from '../../../src/component';

class TestComp extends Component { render() { return 'test'; } }

describe('Scope', () => {
  it('should register components', () => {
    const scope = createScope('test');
    scope.register('Test', TestComp);

    expect(scope.has('Test')).toBe(true);
    expect(scope.get('Test')).toBe(TestComp);
  });

  it('should inherit from parent', () => {
    const parent = createScope('parent');
    parent.register('Parent', TestComp);

    const child = createScope('child', parent);
    expect(child.has('Parent')).toBe(true);
  });

  it('should list own components separately', () => {
    const parent = createScope('parent');
    parent.register('Parent', TestComp);

    const child = createScope('child', parent);
    child.register('Child', TestComp);

    expect(child.listOwn()).toEqual(['Child']);
    expect(child.listAll()).toContain('Parent');
    expect(child.listAll()).toContain('Child');
  });
});
